http:
  port: 9093
postgres:
  connectionString: postgres://localhost:5432/casino_transactions?sslmode=disable
  user: postgres
  password: "123456"
  maxOpenConns: 25
  maxIdleConns: 5
  maxConnLifetime: 5
kafka:
  connectionString: localhost:9092
  user:
  password:
  topic: transaction-events
  groupId: transaction-consumer
