producer:
  initialBatchSize: 15
  creationRPS: 1
  distinctUsers: 1
  amountFrom: 10
  amountTo: 10000
kafka:
  connectionString: localhost:9092
  user:
  password:
  topic: transaction-events
  groupId: transaction-producer
  requiredAcks: 1
  maxAttempts: 10